name: WildWands
version: '${project.version}'
main: me.emiel04.wildwands.WildWands
author: emiel04
api-version: '1.20'
softdepend:  [Vault]
commands:
  wildwands:
    description: Base command for WildWands
    aliases:
      - ww
    usage: /<command>